apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: {{ printf "%s/datacatalog_backend:%s" .Values.images.repository .Values.images.tag | quote }}
        ports:
        - containerPort: 8090
        env:
        - name: DB_URL
          value: {{ printf "jdbc:postgresql://datacatalogdb:5432/%s" .Values.datacatalogDb.db | quote }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: datacatalog-secrets
              key: db.user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datacatalog-secrets
              key: db.password
        - name: AUTHENTICATION
          value: {{ ternary "1" "0" .Values.backend.authentication | quote }}
        - name: PUBLIC_HOST
          value: {{ printf "https://%s" .Values.global.publicHost | quote }}
        - name: DQT_URL
          value: "http://data-quality-tool:8000"
        - name: KEYCLOAK_AUTH_URL
          value: {{ .Values.backend.keycloak.authUrl | quote }}
        - name: KEYCLOAK_REALM
          value: {{ .Values.backend.keycloak.realm | quote }}
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: datacatalog-secrets
              key: keycloak.client-id
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: datacatalog-secrets
              key: keycloak.client-secret
        - name: KEYCLOAK_SSL_REQUIRED
          value: {{ .Values.backend.keycloak.sslRequired | quote }}
        startupProbe:
          httpGet:
            path: /services/actuator/health
            port: 8090
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /services/actuator/health
            port: 8090
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /services/actuator/health
            port: 8090
          periodSeconds: 30
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
