cluster:
  managed: false
  storageClasses:
    local: k8s-local-storage
    managed: ceph-corbo-cephfs-retain

images:
  repository: hbpmip
  tag: 2.0.0

global:
  publicHost: datacatalogue.mip.ebrains.eu

frontend:
  ingress:
    className: haproxy-public
    clusterIssuer: letsencrypt-public
    tlsSecretName: datacatalog-tls

dqt:
  flaskEnv: development
  flaskDebug: '1'

datacatalogDb:
  image: postgres:18.3
  db: datacatalog
  storage: 5Gi

backend:
  authentication: true
  keycloak:
    authUrl: https://iam.ebrains.eu/auth/
    realm: MIP
    sslRequired: none
