name: Converter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry==2.2.1"

      - name: Install dependencies
        run: |
          poetry install --no-interaction
        working-directory: data_quality_tool

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          poetry run coverage run -m pytest
          poetry run coverage xml
        working-directory: data_quality_tool

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          fail_ci_if_error: true
          verbose: true
